### PR TITLE
Added auth to be singleton as storage provider

### PR DESCRIPTION
**Pull request by makylfang**

### CODE REVIEW

**Review by mmjee — APPROVED** [review]

**Comment by mmjee** [comment]
I don't see the benefit, but I suppose, why not…

**Comment by makylfang** [comment]
@mmjee When someone clones the repo, adds the routes then on navigating- there will be multiple frames of auth on top of each other.

**Comment by mmjee** [comment]
I expected developers to extend the current implementation by hierarchically passing down the instance, since returning the singleton is an asynchronous process, needlessly increasing complexity in places that require the instance. Either way, no big deal.

Regards,

**Comment by mmjee** [comment]
I expected developers to extend the current implementation by hierarchically passing down the instance, since returning the singleton is an asynchronous process, needlessly increasing complexity in places that require the instance. Either way, no big deal.

Regards,

**Pull request merged**
